language: ruby
cache: bundler

sudo: false

branches:
  only:
    - master

before_install:
  - gem update --system
  - gem install bundler
  - bundle --version
  - gem --version
rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - ruby-head

allow_failures:
  - rvm: ruby-head

script:
  - bundle exec chefstyle
  - bundle exec rake spec
  - bundle exec ohai
